apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-podman-testing
spec:
  vendor: eduk8s.io
  title: Podman Testing
  description: Play area for testing podman
  url: https://github.com/eduk8s-tests/lab-podman-testing
  content:
    image: quay.io/eduk8s-tests/lab-podman-testing:master
  duration: 1h
  session:
    budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      registry:
        enabled: true
    patches:
      containers:
      - name: workshop
        resources:
          requests:
            memory: 256Mi
          limits:
            memory: 768Mi
        securityContext:
          privileged: true
        volumeMounts:
        - name: podman
          mountPath: /run/containers
          subPath: run-containers
        - name: podman
          mountPath: /var/lib/containers
          subPath: var-lib-containers
      volumes:
      - name: podman
        persistentVolumeClaim:
          claimName: $(session_namespace)-podman
    objects:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        namespace: $(workshop_namespace)
        name: $(session_namespace)-podman
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        namespace: $(workshop_namespace)
        name: $(session_namespace)-podman
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: $(workshop_namespace)-podman
      subjects:
      - kind: ServiceAccount
        namespace: $(workshop_namespace)
        name: $(service_account)
  environment:
    objects:
    - apiVersion: policy/v1beta1
      kind: PodSecurityPolicy
      metadata:
        name: $(workshop_namespace)-podman
      spec:
        privileged: true
        allowPrivilegeEscalation: true
        requiredDropCapabilities:
        - KILL
        - MKNOD
        hostIPC: false
        hostNetwork: false
        hostPID: false
        hostPorts: []
        runAsUser:
          rule: MustRunAsNonRoot
        seLinux:
          rule: RunAsAny
        fsGroup:
          rule: RunAsAny
        supplementalGroups:
          rule: RunAsAny
        volumes:
        - configMap
        - downwardAPI
        - emptyDir
        - persistentVolumeClaim
        - projected
        - secret
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: $(workshop_namespace)-podman
      rules:
      - apiGroups:
        - policy
        resources:
        - podsecuritypolicies
        verbs:
        - use
        resourceNames:
        - $(workshop_namespace)-podman
